Repository Lotte-Feelmycode/the-parabole-mono-be, pull requests merged in 2022-09, with the labels that each got.

#25 상품목록 API 제작
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/feelmycode/parabole/ParaboleApplication.java
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/BaseEntity.java
  src/main/java/com/feelmycode/parabole/repository/ProductRepository.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
Labels: Docs, Feat

#29 상품 API 제작
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/Product.java
  src/main/java/com/feelmycode/parabole/domain/ProductDetail.java
  src/main/java/com/feelmycode/parabole/repository/ProductRepository.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
  src/test/java/com/feelmycode/parabole/service/ProductServiceTest.java
Labels: Feat

#30 [feature/eventapply] 이벤트 응모 구현
  build.gradle
  src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
  src/main/java/com/feelmycode/parabole/controller/testController.java
  src/main/java/com/feelmycode/parabole/domain/EventParticipant.java
  src/main/java/com/feelmycode/parabole/dto/DTO.java
  src/main/java/com/feelmycode/parabole/dto/EventApplyDto.java
  src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
  src/main/java/com/feelmycode/parabole/repository/EventPrizeRepository.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
  src/main/java/com/feelmycode/parabole/service/testService.java
Labels: Feat

#39 [feature/product] !Hotfix!
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
Labels: !HOTFIX

#37 [feature/event] 이벤트 CRUD API 구현
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/domain/BaseEntity.java
  src/main/java/com/feelmycode/parabole/domain/Event.java
  src/main/java/com/feelmycode/parabole/domain/EventImage.java
  src/main/java/com/feelmycode/parabole/domain/EventPrize.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/EventDto.java
  src/main/java/com/feelmycode/parabole/dto/EventListResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/EventPrizeCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/repository/EventRepository.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
  src/test/java/com/feelmycode/parabole/service/eventServiceTest.java
Labels: Feat

#43 [feature/eventapply] 이벤트 응모 API 수정, 코드 스타일 변경 [#16]
  build.gradle
  src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
  src/main/java/com/feelmycode/parabole/domain/EventParticipant.java
  src/main/java/com/feelmycode/parabole/dto/EventApplyDto.java
  src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
Labels: Style

#40 [Feature/response] response entity 와 커스텀 error 생성
  src/main/java/com/feelmycode/parabole/global/api/ParaboleResponse.java
  src/main/java/com/feelmycode/parabole/global/error/ParaboleExceptionHandler.java
  src/main/java/com/feelmycode/parabole/global/error/exception/ParaboleException.java
Labels: Feat

#33 [feature/coupon] Coupon Api 기능 구현
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/BaseEntity.java
  src/main/java/com/feelmycode/parabole/domain/Coupon.java
  src/main/java/com/feelmycode/parabole/domain/CouponType.java
  src/main/java/com/feelmycode/parabole/domain/CouponUseState.java
  src/main/java/com/feelmycode/parabole/domain/Seller.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/domain/UserCoupon.java
  src/main/java/com/feelmycode/parabole/dto/CouponAssignRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponAvailianceResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
  src/main/java/com/feelmycode/parabole/global/util/UuidApp.java
  src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
  src/main/java/com/feelmycode/parabole/repository/SellerRepository.java
  src/main/java/com/feelmycode/parabole/repository/UserCouponRepository.java
  src/main/java/com/feelmycode/parabole/repository/UserRepository.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/SellerService.java
Labels: Feat

#49 [Feature/productList] Product에 Response Entity 및 Custom Error 적용
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/global/error/TestError.java
  src/main/java/com/feelmycode/parabole/global/error/exception/ExampleException.java
  src/main/java/com/feelmycode/parabole/global/error/exception/NoDataException.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
Labels: Fix

#54 [Fix/event] Event에 Response Entity 및 Custom Error 적용
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/domain/EventPrize.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/EventListResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/EventPrizeCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
  src/test/java/com/feelmycode/parabole/service/eventServiceTest.java
Labels: Fix

#63 [feature/setting] Spring Rest Docs, Logging설정 추가 및 테스트
  build.gradle
  src/docs/asciidoc/example.adoc
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/resources/log4j2.xml
  src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
Labels: Feat

#55 [feat/coupon] Coupon에 Response Entity 및 Custom Error 적용
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/dto/CouponUseAndAssignRequestDto.java
  src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
  src/main/java/com/feelmycode/parabole/repository/UserCouponRepository.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
Labels: Fix

#59 WIP [feature/user] User 회원가입, 로그인 API
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/dto/UserSigninDto.java
  src/main/java/com/feelmycode/parabole/dto/UserSignupDto.java
  src/main/java/com/feelmycode/parabole/repository/UserRepository.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#67 [feature/user] User, Seller Entity와 기본 기능 추가
  src/main/java/com/feelmycode/parabole/controller/SellerController.java
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/domain/Seller.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/dto/SellerInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/SellerRegisterDto.java
  src/main/java/com/feelmycode/parabole/dto/UserSignupDto.java
  src/main/java/com/feelmycode/parabole/enumtype/Role.java
  src/main/java/com/feelmycode/parabole/repository/SellerRepository.java
  src/main/java/com/feelmycode/parabole/repository/UserRepository.java
  src/main/java/com/feelmycode/parabole/service/SellerService.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#64 [feature/cart] Cart CRUD , ResponseEntity 및 Custom Error 적용
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/domain/Cart.java
  src/main/java/com/feelmycode/parabole/domain/CartItem.java
  src/main/java/com/feelmycode/parabole/dto/CartItemDto.java
  src/main/java/com/feelmycode/parabole/dto/CartItemRequestDto.java
  src/main/java/com/feelmycode/parabole/repository/CartItemRepository.java
  src/main/java/com/feelmycode/parabole/repository/CartRepository.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
  src/main/java/com/feelmycode/parabole/service/CartService.java
Labels: Feat

#71 [feature/user] User 마이페이지에서 개인정보 반환
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/dto/UserInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#73 [Feature/eventapply] 이벤트 응모 ResponseEntity 및 예외처리 추가
  src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
  src/main/java/com/feelmycode/parabole/domain/EventParticipant.java
  src/main/java/com/feelmycode/parabole/dto/EventApplyDto.java
  src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
Labels: Fix, Feat

#77 [feature/product] Product와 ProductDetail기능 추가
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/Product.java
  src/main/java/com/feelmycode/parabole/domain/ProductDetailRepository.java
  src/main/java/com/feelmycode/parabole/dto/ProductDetailListResponseDto.java
  src/main/java/com/feelmycode/parabole/service/ProductDetailService.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
  src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
  src/test/java/com/feelmycode/parabole/service/ProductServiceTest.java
Labels: Feat

#36 [feature/order] 주문 CRUD작성
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
  src/main/java/com/feelmycode/parabole/domain/Order.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/repository/OrderInfoRepository.java
  src/main/java/com/feelmycode/parabole/repository/OrderRepository.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
Labels: Fix, Feat

#80 [feature/order] OrderInfoListDto 추가
  src/main/java/com/feelmycode/parabole/dto/OrderInfoListDto.java
  src/main/java/com/feelmycode/parabole/repository/OrderRepository.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
Labels: Feat

#75 [feature/coupon] jpa 적용 작업
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/domain/Coupon.java
  src/main/java/com/feelmycode/parabole/domain/CouponType.java
  src/main/java/com/feelmycode/parabole/domain/CouponUseState.java
  src/main/java/com/feelmycode/parabole/domain/Seller.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/domain/UserCoupon.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
  src/main/java/com/feelmycode/parabole/enumtype/CouponType.java
  src/main/java/com/feelmycode/parabole/enumtype/CouponUseState.java
  src/main/java/com/feelmycode/parabole/repository/UserCouponRepository.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
  src/test/java/com/feelmycode/parabole/service/UserServiceTest.java
Labels: Refactor

#84 [Feat/CORS] CORS 설정 (개발 서버 배포후 수정예정)
  src/main/java/com/feelmycode/parabole/global/config/TestConfig.java
  src/main/java/com/feelmycode/parabole/global/config/WebMvcConfig.java
Labels: Feat

#85 [feature/coupon] EnumType 사용방법 수정
  src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
  src/main/java/com/feelmycode/parabole/enumtype/CouponUseState.java
Labels: Refactor

#82 [Feature/event-seller] Event-Seller 매핑
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/domain/Event.java
  src/main/java/com/feelmycode/parabole/domain/Seller.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/EventDto.java
  src/main/java/com/feelmycode/parabole/dto/EventListResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/EventPrizeCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
Labels: Fix

#90 [feature/coupon] CouponController 에서 sellerId 를 Arg로 받는 API 전부 userId 로 로직 수정
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/domain/Coupon.java
  src/main/java/com/feelmycode/parabole/domain/UserCoupon.java
  src/main/java/com/feelmycode/parabole/dto/CouponAvailianceResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
Labels: Feat
