Repository Lotte-Feelmycode/the-parabole-mono-be, pull requests merged in 2022-10, with the labels that each got.

#92 [feature/user] 계정의 Role 확인 및 반환
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/global/error/exception/NotSellerException.java
  src/main/java/com/feelmycode/parabole/service/SellerService.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#95 [feature/user] User 에 연락처 추가
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/dto/UserSignupDto.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#93 [Feature/productList] 상품목록 조회 에러 수정(response를 dto로 변경)
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/TestDomain.java
  src/main/java/com/feelmycode/parabole/dto/ProductDetailDto.java
  src/main/java/com/feelmycode/parabole/dto/ProductDetailListResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/ProductDto.java
  src/main/java/com/feelmycode/parabole/global/util/StringUtil.java
  src/main/java/com/feelmycode/parabole/global/util/TestUtil.java
  src/main/java/com/feelmycode/parabole/repository/ProductDetailRepository.java
  src/main/java/com/feelmycode/parabole/repository/TestRespostory.java
  src/main/java/com/feelmycode/parabole/service/ProductDetailService.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
Labels: Fix

#98 [Feature/event] Seller ID > User ID로 API 파라미터 수정, @Valid 유효성 체크 추가
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/EventDto.java
  src/main/java/com/feelmycode/parabole/dto/EventListResponseDto.java
  src/main/java/com/feelmycode/parabole/repository/EventRepository.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
Labels: Fix, Feat

#101 [feature/event] @NotNull import 수정, 사용하지 않는 import 제거
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/domain/EventPrize.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/EventDto.java
  src/main/java/com/feelmycode/parabole/dto/EventListResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/EventPrizeCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
  src/test/java/com/feelmycode/parabole/service/eventServiceTest.java
Labels: Fix, Chore

#119 [feat/coupon] 쿠폰 목록 조회 , 쿠폰 등록 API 수정
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/domain/Coupon.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#114 [feature/order] 주문 기능 추가
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
  src/main/java/com/feelmycode/parabole/domain/Order.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/domain/Product.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoListDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/enumtype/OrderPayState.java
  src/main/java/com/feelmycode/parabole/enumtype/OrderState.java
  src/main/java/com/feelmycode/parabole/repository/OrderInfoRepository.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
Labels: Feat

#120 [Feature/productDetailApi] 주문 및 장바구니 기능 수정
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/domain/CartItem.java
  src/main/java/com/feelmycode/parabole/dto/CartAddItemRequestDto.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
  src/main/java/com/feelmycode/parabole/service/CartService.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#132 [Feature/event-searchOptions] 이벤트 응모내역 및 이벤트 검색조건 조회 구현
  src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/dto/EventParticipantDto.java
  src/main/java/com/feelmycode/parabole/dto/EventSearchRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/EventSearchResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/UserDto.java
  src/main/java/com/feelmycode/parabole/enumtype/EventStatus.java
  src/main/java/com/feelmycode/parabole/enumtype/EventType.java
  src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
  src/main/java/com/feelmycode/parabole/repository/EventRepository.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
Labels: Feat

#134 [Feature/cart] 장바구니 알고리즘 수정
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/controller/SellerController.java
  src/main/java/com/feelmycode/parabole/domain/Cart.java
  src/main/java/com/feelmycode/parabole/dto/CartItemDeleteRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CartItemDto.java
  src/main/java/com/feelmycode/parabole/dto/CartItemGetResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CartItemUpdateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/SellerDto.java
  src/main/java/com/feelmycode/parabole/repository/CartItemRepository.java
  src/main/java/com/feelmycode/parabole/repository/CartRepository.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
  src/main/java/com/feelmycode/parabole/service/CartService.java
  src/main/java/com/feelmycode/parabole/service/SellerService.java
Labels: Fix, Feat

#122 [feature/coupon] Seller Coupon List Dto 에 couponId 추가, 쿠폰에서 user 조회시 필요한 API 추가
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/EventPrizeDto.java
  src/main/java/com/feelmycode/parabole/dto/UserInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/repository/UserRepository.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#135 [feature/cart_controller]Fix: 장바구니 삭제 메서드 수정
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/dto/CartItemDeleteRequestDto.java
  src/main/java/com/feelmycode/parabole/repository/CartItemRepository.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
Labels: Fix

#138 [Fix/seller-event] 이벤트 응모 리스트 반환 dto 수정
  src/main/java/com/feelmycode/parabole/dto/EventParticipantDto.java
Labels: Fix

#125 [feature/order] 주문등록 확인 및 enum 수정
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/dto/EventListResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoListDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoSimpleDto.java
  src/main/java/com/feelmycode/parabole/enumtype/OrderPayState.java
  src/main/java/com/feelmycode/parabole/repository/OrderRepository.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
Labels: Feat

#139 [feature/coupon] 사용자에게 쿠폰을 배정해주는 API
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/domain/Coupon.java
  src/main/java/com/feelmycode/parabole/dto/CouponAssignRequestDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
Labels: Feat

#137 [Feat/eventapplyinfo] 사용자 이벤트 상세페이지 BE 구현
  src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
  src/main/java/com/feelmycode/parabole/dto/EventDto.java
  src/main/java/com/feelmycode/parabole/dto/EventParticipantUserDto.java
  src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
Labels: Feat

#142 [feature/order] 코드 정리
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
Labels: Fix

#141 [feature/coupon] 쿠폰 출력 정보 dto 수정
  src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
Labels: Feat

#145 [feature/order] 주문이 생성되는 로직 수정
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
  src/main/java/com/feelmycode/parabole/domain/Order.java
  src/main/java/com/feelmycode/parabole/repository/OrderRepository.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
  src/main/java/com/feelmycode/parabole/service/UpdateService.java
Labels: Feat

#150 [feature/setting] 테스트 코드와 rest docs 예제
  build.gradle
  src/docs/asciidoc/example.adoc
  src/docs/asciidoc/example.html
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/Seller.java
  src/main/java/com/feelmycode/parabole/dto/ProductDto.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
  src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
Labels: Feat

#152 [feature/events] 이벤트 검색 조건 목록 조회 오류 수정
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/repository/EventRepository.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
Labels: Fix

#146 [feature/cart coupon] 장바구니에서 상품과 쿠폰을 셀러별로 정리하여 보냄
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/domain/UserCoupon.java
  src/main/java/com/feelmycode/parabole/dto/CartWithCouponResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponInfoDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponResponseDto.java
  src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
Labels: Feat

#161 [feature/eventdetail] 이벤트상품 쿠폰 타입 추가
  src/main/java/com/feelmycode/parabole/dto/EventPrizeDto.java
Labels: Fix
