Repository Lotte-Feelmycode/the-parabole-mono-be, pull requests merged in 2022-11, with the labels that each got.

#167 [feature/cartRestDocs] 상품목록, 장바구니 restdocs 추가
  build.gradle
  src/docs/asciidoc/example.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/snippets/cart-delete/curl-request.adoc
  src/docs/asciidoc/snippets/cart-delete/http-request.adoc
  src/docs/asciidoc/snippets/cart-delete/http-response.adoc
  src/docs/asciidoc/snippets/cart-delete/httpie-request.adoc
  src/docs/asciidoc/snippets/cart-delete/request-body.adoc
  src/docs/asciidoc/snippets/cart-delete/request-parameters.adoc
  src/docs/asciidoc/snippets/cart-delete/response-body.adoc
  src/docs/asciidoc/snippets/cart-delete/response-fields.adoc
  src/docs/asciidoc/snippets/cart-list/curl-request.adoc
  src/docs/asciidoc/snippets/cart-list/http-request.adoc
  src/docs/asciidoc/snippets/cart-list/http-response.adoc
  src/docs/asciidoc/snippets/cart-list/httpie-request.adoc
  src/docs/asciidoc/snippets/cart-list/request-body.adoc
  src/docs/asciidoc/snippets/cart-list/request-parameters.adoc
  src/docs/asciidoc/snippets/cart-list/response-body.adoc
  src/docs/asciidoc/snippets/cart-list/response-fields.adoc
  src/docs/asciidoc/snippets/cart-product-add/curl-request.adoc
  src/docs/asciidoc/snippets/cart-product-add/http-request.adoc
  src/docs/asciidoc/snippets/cart-product-add/http-response.adoc
  src/docs/asciidoc/snippets/cart-product-add/httpie-request.adoc
  src/docs/asciidoc/snippets/cart-product-add/request-body.adoc
  src/docs/asciidoc/snippets/cart-product-add/request-fields.adoc
  src/docs/asciidoc/snippets/cart-product-add/response-body.adoc
  src/docs/asciidoc/snippets/cart-product-add/response-fields.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/curl-request.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/http-request.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/http-response.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/httpie-request.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/request-body.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/request-fields.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/response-body.adoc
  src/docs/asciidoc/snippets/cart-update-cnt/response-fields.adoc
  src/docs/asciidoc/snippets/product-list/curl-request.adoc
  src/docs/asciidoc/snippets/product-list/http-request.adoc
  src/docs/asciidoc/snippets/product-list/http-response.adoc
  src/docs/asciidoc/snippets/product-list/httpie-request.adoc
  src/docs/asciidoc/snippets/product-list/request-body.adoc
  src/docs/asciidoc/snippets/product-list/request-parameters.adoc
  src/docs/asciidoc/snippets/product-list/response-body.adoc
  src/docs/asciidoc/snippets/product-list/response-fields.adoc
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/dto/CartAddItemRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CartWithCouponResponseDto.java
  src/main/java/com/feelmycode/parabole/repository/ProductRepository.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/feelmycode/parabole/controller/CartControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
  src/test/java/com/feelmycode/parabole/service/ProductServiceTest.java
Labels: Docs, Feat

#174 [feature/order_coupon] 주문과 쿠폰 연결
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
  src/main/java/com/feelmycode/parabole/dto/CartResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/CartWithCouponResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderWithCouponResponseDto.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
Labels: Feat

#171 [feature/eventapply restdocs] 이벤트 레스트 독스 생성
  src/docs/asciidoc/example.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/curl-request.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/http-request.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/http-response.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/httpie-request.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/request-body.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/request-fields.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/response-body.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/response-fields.adoc
  src/docs/asciidoc/snippets/eventparticipant/curl-request.adoc
  src/docs/asciidoc/snippets/eventparticipant/http-request.adoc
  src/docs/asciidoc/snippets/eventparticipant/http-response.adoc
  src/docs/asciidoc/snippets/eventparticipant/httpie-request.adoc
  src/docs/asciidoc/snippets/eventparticipant/request-body.adoc
  src/docs/asciidoc/snippets/eventparticipant/request-fields.adoc
  src/docs/asciidoc/snippets/eventparticipant/response-body.adoc
  src/docs/asciidoc/snippets/eventparticipant/response-fields.adoc
  src/docs/asciidoc/snippets/seller-eventparticipant/curl-request.adoc
  src/docs/asciidoc/snippets/seller-eventparticipant/http-request.adoc
  src/docs/asciidoc/snippets/seller-eventparticipant/http-response.adoc
  src/docs/asciidoc/snippets/seller-eventparticipant/httpie-request.adoc
  src/docs/asciidoc/snippets/seller-eventparticipant/request-body.adoc
  src/docs/asciidoc/snippets/seller-eventparticipant/response-body.adoc
  src/docs/asciidoc/snippets/seller-eventparticipant/response-fields.adoc
  src/docs/asciidoc/snippets/user-eventparticipant/curl-request.adoc
  src/docs/asciidoc/snippets/user-eventparticipant/http-request.adoc
  src/docs/asciidoc/snippets/user-eventparticipant/http-response.adoc
  src/docs/asciidoc/snippets/user-eventparticipant/httpie-request.adoc
  src/docs/asciidoc/snippets/user-eventparticipant/request-body.adoc
  src/docs/asciidoc/snippets/user-eventparticipant/response-body.adoc
  src/docs/asciidoc/snippets/user-eventparticipant/response-fields.adoc
  src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
  src/test/java/com/feelmycode/parabole/controller/EventApplyControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
  src/test/java/com/feelmycode/parabole/service/eventServiceTest.java
Labels: Docs

#177 [feature/order coupon] 주문에서 쿠폰을 사용하는 기능 추가
  src/docs/asciidoc/example.adoc
  src/docs/asciidoc/snippets/create-orderinfo/curl-request.adoc
  src/docs/asciidoc/snippets/create-orderinfo/http-request.adoc
  src/docs/asciidoc/snippets/create-orderinfo/http-response.adoc
  src/docs/asciidoc/snippets/create-orderinfo/httpie-request.adoc
  src/docs/asciidoc/snippets/get-order-list/curl-request.adoc
  src/docs/asciidoc/snippets/get-order-list/http-request.adoc
  src/docs/asciidoc/snippets/get-order-list/httpie-request.adoc
  src/docs/asciidoc/snippets/get-order-list/request-body.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-seller/curl-request.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-seller/http-request.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-seller/http-response.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-seller/httpie-request.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-seller/request-body.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-seller/response-body.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-seller/response-fields.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-user/curl-request.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-user/http-request.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-user/http-response.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-user/httpie-request.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-user/request-body.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-user/response-body.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list-by-user/response-fields.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list/http-response.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list/request-fields.adoc
  src/docs/asciidoc/snippets/get-orderinfo-list/response-body.adoc
  src/docs/asciidoc/snippets/update-order-delivery/curl-request.adoc
  src/docs/asciidoc/snippets/update-order-delivery/http-request.adoc
  src/docs/asciidoc/snippets/update-order-delivery/http-response.adoc
  src/docs/asciidoc/snippets/update-order-delivery/httpie-request.adoc
  src/docs/asciidoc/snippets/update-order/curl-request.adoc
  src/docs/asciidoc/snippets/update-order/http-request.adoc
  src/docs/asciidoc/snippets/update-order/http-response.adoc
  src/docs/asciidoc/snippets/update-order/httpie-request.adoc
  src/docs/asciidoc/snippets/update-order/request-body.adoc
  src/docs/asciidoc/snippets/update-order/response-body.adoc
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/dto/CouponInfoDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoRequestListDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderUpdateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/UpdateService.java
  src/test/java/com/feelmycode/parabole/controller/OrderControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/OrderInfoControllerTest.java
Labels: Docs, Feat

#178 [feature/order] 상세 주문정보 못 가져오는 부분 수정
  src/main/java/com/feelmycode/parabole/dto/OrderBySellerDto.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
Labels: !HOTFIX

#182 [feature/cart_rest_docs] 장바구니 목록보기 restdocs 수정
  src/docs/asciidoc/snippets/cart-list/curl-request.adoc
  src/docs/asciidoc/snippets/cart-list/http-request.adoc
  src/docs/asciidoc/snippets/cart-list/http-response.adoc
  src/docs/asciidoc/snippets/cart-list/httpie-request.adoc
  src/docs/asciidoc/snippets/cart-list/response-body.adoc
  src/docs/asciidoc/snippets/cart-list/response-fields.adoc
  src/main/resources/static/docs/index.html
  src/test/java/com/feelmycode/parabole/controller/CartControllerTest.java
Labels: Fix, Docs

#187 [feature/order] 재고와 썸네일 가져오는 코드 추가
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/domain/Order.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/dto/OrderDeliveryUpdateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderRequestDto.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/UpdateService.java
  src/test/java/com/feelmycode/parabole/controller/OrderControllerTest.java
Labels: Feat

#186 [feature/event] 셀러 오피스 이벤트 스케쥴 조회 API 구현
  src/docs/asciidoc/event.adoc
  src/docs/asciidoc/snippets/event-scheduler/curl-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/http-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/http-response.adoc
  src/docs/asciidoc/snippets/event-scheduler/httpie-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/request-body.adoc
  src/docs/asciidoc/snippets/event-scheduler/response-body.adoc
  src/docs/asciidoc/snippets/event-scheduler/response-fields.adoc
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
  src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
Labels: Docs, Feat

#189 [feature/auth] Jwt 를 이용한 기본 회원가입 로그인 구현
  build.gradle
  src/main/java/com/feelmycode/parabole/controller/AuthController.java
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/dto/UserDto.java
  src/main/java/com/feelmycode/parabole/dto/UserLoginResponseDto.java
  src/main/java/com/feelmycode/parabole/global/config/JwtAuthenticationFilter.java
  src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
  src/main/java/com/feelmycode/parabole/global/error/exception/NoSuchAccountException.java
  src/main/java/com/feelmycode/parabole/global/util/JwtUtils.java
  src/main/java/com/feelmycode/parabole/repository/UserRepository.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#194 [feature/oauthgoogle] 구글 로그인 구현
  src/main/java/com/feelmycode/parabole/controller/AuthController.java
  src/main/java/com/feelmycode/parabole/domain/GoogleOauthToken.java
  src/main/java/com/feelmycode/parabole/domain/GoogleProfile.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#198 [feature/eventmsa] 이벤트서버 분리를 위한 초기 세팅 구현
  build.gradle
  src/main/java/com/feelmycode/parabole/ParaboleApplication.java
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/dto/CouponDto.java
  src/main/java/com/feelmycode/parabole/dto/ProductResponseDto.java
Labels: Feat

#195 [feature/oauthnaver] 네이버 로그인 구현
  src/main/java/com/feelmycode/parabole/controller/AuthController.java
  src/main/java/com/feelmycode/parabole/domain/NaverOauthToken.java
  src/main/java/com/feelmycode/parabole/domain/NaverProfile.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#196 [feature/oauthkakao] 카카오 로그인 구현
  src/main/java/com/feelmycode/parabole/controller/AuthController.java
  src/main/java/com/feelmycode/parabole/domain/KakaoOauthToken.java
  src/main/java/com/feelmycode/parabole/domain/KakaoProfile.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#200 [feature/seller] 사용자를 판매자로 전환하는 API 구현
  src/main/java/com/feelmycode/parabole/controller/UserController.java
  src/main/java/com/feelmycode/parabole/domain/Seller.java
  src/main/java/com/feelmycode/parabole/domain/User.java
  src/main/java/com/feelmycode/parabole/dto/UserToSellerDto.java
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Feat

#199 [feature/event-scheduler] 이벤트 등록 스케쥴 검증 API 구현
  src/docs/asciidoc/event.adoc
  src/docs/asciidoc/snippets/event-create-check/curl-request.adoc
  src/docs/asciidoc/snippets/event-create-check/http-request.adoc
  src/docs/asciidoc/snippets/event-create-check/http-response.adoc
  src/docs/asciidoc/snippets/event-create-check/httpie-request.adoc
  src/docs/asciidoc/snippets/event-create-check/request-body.adoc
  src/docs/asciidoc/snippets/event-create-check/request-parameters.adoc
  src/docs/asciidoc/snippets/event-create-check/response-body.adoc
  src/docs/asciidoc/snippets/event-create-check/response-fields.adoc
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
  src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
Labels: Docs, Feat

#201 [feature/auth-event] user id로 이벤트 목록 조회하는 API 인증 변경 작업
  src/docs/asciidoc/snippets/event-all/curl-request.adoc
  src/docs/asciidoc/snippets/event-all/http-request.adoc
  src/docs/asciidoc/snippets/event-all/http-response.adoc
  src/docs/asciidoc/snippets/event-all/httpie-request.adoc
  src/docs/asciidoc/snippets/event-all/response-body.adoc
  src/docs/asciidoc/snippets/event-all/response-fields.adoc
  src/docs/asciidoc/snippets/event-create-check/curl-request.adoc
  src/docs/asciidoc/snippets/event-create-check/http-request.adoc
  src/docs/asciidoc/snippets/event-create-check/http-response.adoc
  src/docs/asciidoc/snippets/event-create-check/httpie-request.adoc
  src/docs/asciidoc/snippets/event-create-check/request-parameters.adoc
  src/docs/asciidoc/snippets/event-create/curl-request.adoc
  src/docs/asciidoc/snippets/event-create/http-request.adoc
  src/docs/asciidoc/snippets/event-create/http-response.adoc
  src/docs/asciidoc/snippets/event-create/httpie-request.adoc
  src/docs/asciidoc/snippets/event-create/request-body.adoc
  src/docs/asciidoc/snippets/event-create/request-fields.adoc
  src/docs/asciidoc/snippets/event-create/response-body.adoc
  src/docs/asciidoc/snippets/event-delete/curl-request.adoc
  src/docs/asciidoc/snippets/event-delete/http-request.adoc
  src/docs/asciidoc/snippets/event-delete/http-response.adoc
  src/docs/asciidoc/snippets/event-delete/httpie-request.adoc
  src/docs/asciidoc/snippets/event-id/curl-request.adoc
  src/docs/asciidoc/snippets/event-id/http-request.adoc
  src/docs/asciidoc/snippets/event-id/http-response.adoc
  src/docs/asciidoc/snippets/event-id/httpie-request.adoc
  src/docs/asciidoc/snippets/event-id/response-body.adoc
  src/docs/asciidoc/snippets/event-scheduler/curl-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/http-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/http-response.adoc
  src/docs/asciidoc/snippets/event-scheduler/httpie-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/response-body.adoc
  src/docs/asciidoc/snippets/event-search/curl-request.adoc
  src/docs/asciidoc/snippets/event-search/http-request.adoc
  src/docs/asciidoc/snippets/event-search/http-response.adoc
  src/docs/asciidoc/snippets/event-search/httpie-request.adoc
  src/docs/asciidoc/snippets/event-search/response-body.adoc
  src/docs/asciidoc/snippets/event-sellerId/curl-request.adoc
  src/docs/asciidoc/snippets/event-sellerId/http-request.adoc
  src/docs/asciidoc/snippets/event-sellerId/http-response.adoc
  src/docs/asciidoc/snippets/event-sellerId/httpie-request.adoc
  src/docs/asciidoc/snippets/event-sellerId/response-body.adoc
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/domain/Event.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
  src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
  src/test/java/com/feelmycode/parabole/service/eventServiceTest.java
Labels: Docs, Feat

#202 [feature/couponjwt] 컨트롤러 header 로 받기
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CouponUseAndAssignRequestDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
Labels: Feat

#163 [feature/s3] 이미지 저장
  build.gradle
  src/docs/asciidoc/snippets/event-all/curl-request.adoc
  src/docs/asciidoc/snippets/event-all/http-request.adoc
  src/docs/asciidoc/snippets/event-all/http-response.adoc
  src/docs/asciidoc/snippets/event-all/httpie-request.adoc
  src/docs/asciidoc/snippets/event-all/response-body.adoc
  src/docs/asciidoc/snippets/event-all/response-fields.adoc
  src/docs/asciidoc/snippets/event-create-check/curl-request.adoc
  src/docs/asciidoc/snippets/event-create-check/http-request.adoc
  src/docs/asciidoc/snippets/event-create-check/http-response.adoc
  src/docs/asciidoc/snippets/event-create-check/httpie-request.adoc
  src/docs/asciidoc/snippets/event-create-check/request-parameters.adoc
  src/docs/asciidoc/snippets/event-create/curl-request.adoc
  src/docs/asciidoc/snippets/event-create/http-request.adoc
  src/docs/asciidoc/snippets/event-create/http-response.adoc
  src/docs/asciidoc/snippets/event-create/httpie-request.adoc
  src/docs/asciidoc/snippets/event-create/request-body.adoc
  src/docs/asciidoc/snippets/event-create/request-fields.adoc
  src/docs/asciidoc/snippets/event-create/response-body.adoc
  src/docs/asciidoc/snippets/event-delete/curl-request.adoc
  src/docs/asciidoc/snippets/event-delete/http-request.adoc
  src/docs/asciidoc/snippets/event-delete/http-response.adoc
  src/docs/asciidoc/snippets/event-delete/httpie-request.adoc
  src/docs/asciidoc/snippets/event-id/curl-request.adoc
  src/docs/asciidoc/snippets/event-id/http-request.adoc
  src/docs/asciidoc/snippets/event-id/http-response.adoc
  src/docs/asciidoc/snippets/event-id/httpie-request.adoc
  src/docs/asciidoc/snippets/event-id/response-body.adoc
  src/docs/asciidoc/snippets/event-scheduler/curl-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/http-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/http-response.adoc
  src/docs/asciidoc/snippets/event-scheduler/httpie-request.adoc
  src/docs/asciidoc/snippets/event-scheduler/response-body.adoc
  src/docs/asciidoc/snippets/event-search/curl-request.adoc
  src/docs/asciidoc/snippets/event-search/http-request.adoc
  src/docs/asciidoc/snippets/event-search/http-response.adoc
  src/docs/asciidoc/snippets/event-search/httpie-request.adoc
  src/docs/asciidoc/snippets/event-search/response-body.adoc
  src/docs/asciidoc/snippets/event-sellerId/curl-request.adoc
  src/docs/asciidoc/snippets/event-sellerId/http-request.adoc
  src/docs/asciidoc/snippets/event-sellerId/http-response.adoc
  src/docs/asciidoc/snippets/event-sellerId/httpie-request.adoc
  src/docs/asciidoc/snippets/event-sellerId/response-body.adoc
  src/main/java/com/feelmycode/parabole/controller/AwsS3Controller.java
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/Product.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/global/config/WebMvcConfig.java
  src/main/java/com/feelmycode/parabole/service/AwsS3Service.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
  src/main/java/com/feelmycode/parabole/service/ProductDetailService.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
  src/main/resources/application.yml
  src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
Labels: Fix, Docs, Feat

#206 [feature/extract userid] userid 추출
  src/docs/asciidoc/product.adoc
  src/docs/asciidoc/snippets/cart-list/http-response.adoc
  src/docs/asciidoc/snippets/cart-list/response-body.adoc
  src/docs/asciidoc/snippets/get-product/http-response.adoc
  src/docs/asciidoc/snippets/get-product/response-body.adoc
  src/docs/asciidoc/snippets/get-product/response-fields.adoc
  src/docs/asciidoc/snippets/product-list-by-sellerId/http-response.adoc
  src/docs/asciidoc/snippets/product-list-by-sellerId/response-body.adoc
  src/docs/asciidoc/snippets/product-list-by-sellerId/response-fields.adoc
  src/docs/asciidoc/snippets/product-list/http-response.adoc
  src/docs/asciidoc/snippets/product-list/response-body.adoc
  src/docs/asciidoc/snippets/product-list/response-fields.adoc
  src/main/java/com/feelmycode/parabole/controller/CartController.java
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/Order.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/dto/CartAddItemRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/CartItemUpdateRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoListDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/ProductRequestDto.java
  src/main/java/com/feelmycode/parabole/enumtype/OrderInfoState.java
  src/main/java/com/feelmycode/parabole/enumtype/OrderPayState.java
  src/main/java/com/feelmycode/parabole/enumtype/OrderState.java
  src/main/java/com/feelmycode/parabole/service/CartItemService.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
  src/main/java/com/feelmycode/parabole/service/UpdateService.java
  src/test/java/com/feelmycode/parabole/controller/CartControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/OrderControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/OrderInfoControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
Labels: Feat

#207 [feature/jwthotfix] jwt API값 인식 오류 해결
  src/main/java/com/feelmycode/parabole/global/config/JwtAuthenticationFilter.java
Labels: !HOTFIX

#208 [feature/carthotfix] 회원가입 시에 장바구니 추가
  src/main/java/com/feelmycode/parabole/service/UserService.java
Labels: Fix

#205 [feature/migration] 이벤트 서버에서 이벤트 등록 및 취소 시 경품 수량을 처리할 수 있는 API 구현
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
  src/main/java/com/feelmycode/parabole/domain/Coupon.java
  src/main/java/com/feelmycode/parabole/dto/CouponDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/ProductService.java
Labels: Feat

#210 [feature/couponfix] Seller import 추가
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
Labels: Fix

#213 [Feature/deleteHtml] html 파일 삭제되는 설정 추가
  .gitignore
  build.gradle
  src/main/resources/static/docs/cart.html
  src/main/resources/static/docs/event.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/order.html
  src/main/resources/static/docs/product.html
Labels: Chore

#218 [feature/order] 주문 정보 가져오는 부분 수정 및 enum에서 Integer값을 가져오고 저장하도록 변경
  src/docs/asciidoc/index.adoc
  src/main/java/com/feelmycode/parabole/controller/CouponController.java
  src/main/java/com/feelmycode/parabole/controller/OrderController.java
  src/main/java/com/feelmycode/parabole/domain/Order.java
  src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoRequestDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderInfoResponseDto.java
  src/main/java/com/feelmycode/parabole/dto/OrderRequestDto.java
  src/main/java/com/feelmycode/parabole/enumtype/OrderPayState.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
  src/main/java/com/feelmycode/parabole/service/OrderService.java
  src/main/java/com/feelmycode/parabole/service/UpdateService.java
Labels: Feat

#220 HOTFix: 회원가입시 장바구니 생성 안되던 오류 수정
  src/main/java/com/feelmycode/parabole/service/CartService.java
Labels: Fix, !HOTFIX

#222 [feature/mypagecoupon] 마이페이지-나의 쿠폰 목록에 반환값에 sellerId 추가
  src/main/java/com/feelmycode/parabole/dto/CouponUserResponseDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
Labels: Feat

#221 [feature/hotfix-seller-product] 판매자 상품 목록 api 변수 sellerId 로 수정
  src/main/java/com/feelmycode/parabole/controller/ProductController.java
Labels: !HOTFIX

#219 [feature/order_coupon] 주문할 때 사용할 수 있는 쿠폰만 가져오도록 수정, 주문 상세 상태 수정
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/UpdateService.java
Labels: Feat

#224 [fix/usecoupon] 쿠폰 사용 안되는 부분 수정 및 테스트
  src/main/java/com/feelmycode/parabole/dto/CouponUseAndAssignRequestDto.java
  src/main/java/com/feelmycode/parabole/service/CouponService.java
  src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
Labels: Fix

#225 [feature/order] 상품등록 시 이미지가 중복저장되는 부분 해결
  src/main/java/com/feelmycode/parabole/controller/AwsS3Controller.java
Labels: Feat

#235 [dev] 쿠폰이 있을 때 주문상세정보 수정이 안되는 부분 해결
  src/main/java/com/feelmycode/parabole/service/UpdateService.java
Labels: Fix
